# Generated by Django 3.2.9 on 2021-12-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='caption',
            new_name='text',
        ),
    ]
