# Generated by Django 3.2.9 on 2021-12-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_extenduser_image'),
        ('features', '0003_auto_20211206_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.extenduser')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.extenduser')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
